#!/bin/bash
#!/bin/sh
#!/usr/bin/env bash
#!/usr/bin/env sh

set -e

# Help function
# Display script functionality.
Help()
{
    echo "Build your site."
    echo
    echo "Usage: build -[d|p]"
    echo "Options:"
    echo "-d    Build for development mode. \n Use 'serve' script if you want live reload feature."
    echo "-p    Build for production ready site."
}

# Development Build funtion
DevBuild()
{
    echo "Building your site in development mode..."
    # The default is development mode, just reassuring.
    JEKYLL_ENV=development bundle exec jekyll build --config _config.yml
    echo "Done."
}

# Production Build function
ProdBuild()
{
    echo "Building deployment ready site..."
    JEKYLL_ENV=production bundle exec jekyll build --config _config.yml
    echo "Done. Now, copy the contents of 'public' folder into your server."
    echo "If you're gonna deploy it to GitHub Pages, simply pull this repo, set GitHub Pages at Settings tab > Pages and source to 'public'."
}

# Handling Options
while getopts dp options; do
    case $options in
        d) # Invoke DevBuild
        DevBuild
        exit;;
        p) # Invoke ProdBuild
        ProdBuild
        exit;;
        \?) # Invalid option
        echo "OωO: You've entered invalid option."
        exit;;
    esac
done

# Invoke Help
Help
